### ISSUE TITLE
Our docs don't link to the HF leaderboard

### ISSUE THREAD

**Issue by jameslamini** [lamini-ai/lamini-ai.github.io#58]
https://huggingface.co/spaces/lamini/leaderboard

**Comment by bechols** [comment]
As of May 21 this leaderboard is hard to understand unless someone's already very familiar with Lamini (gpt-4 shows up first, so why is Lamini linking to this? these are llama2 models - what about llama3?) - until we address these issues, I don't think it'll help our users to link to this from the docs.

**Comment by bechols** [comment]
@jameslamini just saw you'd changed the title (I thought I'd made a typo). My understanding of the scope here: when the actual leaderboard on HuggingFace gets updated with newer models and is generally clearer about Lamini's models being good, we'll find a place in our docs to add a link. Anything I'm missing?
